#!/bin/bash
unset IFS
set -euf

GH_FORK='mcandre'
APP='buttery'
DEST="$HOME/.local/bin"

fallback() {
    echo "select another install method: https://github.com/$GH_FORK/$APP/blob/main/INSTALL.md" >&2
}

uname_to_go_os() {
    case "$1" in
        Darwin*)
            echo 'darwin'
            ;;
        DragonFly)
            echo 'dragonfly'
            ;;
        FreeBSD*)
            echo 'freebsd'
            ;;
        Linux*)
            echo 'linux'
            ;;
        NetBSD*)
            echo 'netbsd'
            ;;
        OpenBSD*)
            echo 'openbsd'
            ;;
        *illumos*)
            echo 'unknown-illumos'
            ;;
        *)
            echo "error: unsupported os. uname -a: $1" >&2
            fallback
            exit 1
            ;;
    esac
}

uname_arch_to_go_arch() {
    case "$1" in
        aarch64 | arm64)
            echo 'arm64'
            ;;
        amd64 | i86pc | x86_64)
            echo 'amd64'
            ;;
        loongarch64)
            echo 'loong64'
            ;;
        riscv64)
            echo 'riscv64'
            ;;
        *)
            echo "error: unsupported arch. uname -a: $(uname -a)" >&2
            fallback
            exit 1
            ;;
    esac
}

UNAME="$(uname -a)"
OS="$(uname_to_go_os "$UNAME")"
ARCH="$(uname_arch_to_go_arch "$(uname -m)")"
TARBALL="$APP-$OS-$ARCH.tgz"
curl -LO "https://github.com/$GH_FORK/$APP/releases/latest/download/$TARBALL"
mkdir -p "$DEST"
tar -C "$DEST" -xzf "$TARBALL"
rm -rf "$TARBALL"
echo "installed $APP binaries to $DEST"
