#!/bin/bash
unset IFS
set -eufo pipefail

BUCKET='s3://buttery'
VERSION="$(buttery --version)"
DEST="$BUCKET/buttery-$VERSION/"
ARTIFACTS='.rockhopper/artifacts'

# Accelerate connection timeouts
# Reduce console noise
aws() {
    command aws \
        --cli-connect-timeout 1 \
        "$@" \
        >/dev/null
}

aws s3 cp --recursive "$ARTIFACTS" "$DEST"
echo "install media uploaded to \"$DEST\""
